# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 13:48
from __future__ import unicode_literals

import car_leasing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_leasing', '0004_auto_20151206_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to=car_leasing.models.photo_file_path, verbose_name='Фотография'),
        ),
    ]
