# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20151219_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='object_id',
        ),
    ]
